name: ServeRest Automation Tests
on:
  push:
    branches: [main]
  # pull_request:
  #   branches: [ serveRest ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: "0 14 * * *"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  SLACK_BOT_USER_OAUTH_TOKEN: ${{ vars.SLACK_BOT_USER_OAUTH_TOKEN }}

jobs:
  test:
    timeout-minutes: 5
    runs-on: kubernetes-prod
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm run ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run tests
        continue-on-error: true
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: playwright-report/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
