name: ServeRest Tests Automation
on:
  push:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Set environment variables
      run: |
        echo "PLAYWRIGHT_TEST_BASE_URL=https://serverest.dev" >> $GITHUB_ENV
        echo "PLAYWRIGHT_FRONT_URL=https://front.serverest.dev" >> $GITHUB_ENV
        echo "CI_BUILD_ID=${{ github.run_id }}" >> $GITHUB_ENV
        echo "RECORD_KEY=${{ secrets.RECORD_KEY }}" >> $GITHUB_ENV
        echo "PROJECT_ID=${{ secrets.PROJECT_ID }}" >> $GITHUB_ENV

    - name: Debugging Environment Variables
      run: |
        echo "Base API URL: ${{ env.PLAYWRIGHT_TEST_BASE_URL }}"
        echo "Base Frontend URL: ${{ env.PLAYWRIGHT_FRONT_URL }}"
        echo "CI Build ID: ${{ env.CI_BUILD_ID }}"
        echo "Record Key: ${{ env.RECORD_KEY }}"
        echo "Project ID: ${{ env.PROJECT_ID }}"

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test
      env:
        PLAYWRIGHT_TEST_BASE_URL: ${{ env.PLAYWRIGHT_TEST_BASE_URL }}
        PLAYWRIGHT_FRONT_URL: ${{ env.PLAYWRIGHT_FRONT_URL }}
        CI_BUILD_ID: ${{ env.CI_BUILD_ID }}
        RECORD_KEY: ${{ env.RECORD_KEY }}
        PROJECT_ID: ${{ env.PROJECT_ID }}
